description = "최근 커밋의 변경 사항을 분석하고 사용자 영향 및 잠재적 위험을 보고합니다."
prompt = """
# Gemini 보고

## 1. 기술적 변경사항

```diff
!{git diff HEAD~1 HEAD}
```

## 2. 사용자 영향 분석

위 변경사항이 사용자 경험에 어떤 영향을 미칠지 분석해주세요.

## 3. 잠재적 위험 분석

위 변경사항으로 인해 발생할 수 있는 성능, 보안, 기존 기능과의 충돌 등 잠재적 위험이 있다면 간략히 분석해주세요.
"""