description = "UI/UX 개선 지시사항을 구체화하여 작업지시서 초안을 생성합니다."
prompt = """
사용자의 다음 요청을 바탕으로 작업지시서 초안을 작성해주세요:

**사용자 요청:** "{{args}}"

---

**[작업지시서 초안]**

*   **화면 위치**: [예: 상품 상세 페이지]
*   **변경 대상**: [예: '구매하기' 버튼]
*   **요청 사항**: [예: 크기를 20% 키우고, 색상을 브랜드 메인 컬러로 변경하며, 화면 하단에 고정]
*   **요청 이유**: [예: 사용자의 구매 전환율 증가]

---

위 템플릿의 빈칸을 채워서 명확하고 간결한 작업지시서를 완성해줘.
"""